name: CI

on:
  push:

env:
  TEX_NAME: TimEtchellsCV.tex
  PDF_NAME: TimEtchellsCV.pdf

jobs:
  ci:
    name: Build and test
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash

    steps:
      - name: Install latex libraries
        run: |
          sudo apt-get update
          sudo apt-get install texlive texlive-latex-extra texlive-xetex

      - uses: actions/checkout@v2

      - name: Test pdf exists
        run: test -f ${{ env.PDF_NAME }}

      - name: Build pdf
        run: pdflatex -halt-on-error ${{ env.TEX_NAME }}
