name: CI

on:
  push:

env:
  TEX_NAME: TimEtchellsCV.tex
  PDF_NAME: TimEtchellsCV.pdf

jobs:
  ci:
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash

    steps:
      - name: Install latex libraries
        run: |
          sudo apt-get update
          sudo apt-get install texlive texlive-latex-extra texlive-generic-recommended

      - name: Test pdf exists
        run: test -f ${{ env.PDF_NAME }}

      - name: Get existing pdf sha
        run: |
          set -ex
          export PDF_SHA=$(shasum ${{ env.PDF_NAME }} | cut -d' ' -f1)
          echo PDF_SHA=${PDF_SHA} | tee >> $GITHUB_ENV

      - name: Build pdf
        run: pdflatex -halt-on-error ${{ env.TEX_NAME }}

      - name: Get new pdf sha
        run:
          set -ex
          export NEW_PDF_SHA=$(shasum ${{ env.PDF_NAME }} | cut -d' ' -f1)
          echo NEW_PDF_SHA=${NEW_PDF_SHA} | tee >> $GITHUB_ENV

      - name: Test shas match
        run: |
          set -ex
          [[ $NEW_PDF_SHA == $PDF_SHA ]]
